vich_uploader:
    db_driver: orm

    mappings:
       post_image: 
           uri_prefix: '/upload/post'
           upload_destination: '%kernel.project_dir%/public/upload/posts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
